// import "./Day_01/script";
// import "./Day_02/script";
// import "./Day_03/script";
// import "./Day_04/script";
// import "./Day_05/script";
// import "./Day_06/script";
// import "./Day_07/script";
// import "./Day_08/script";
// import "./Day_09/script";
import "./Day_10/script";
